//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFee
    {
        public int Id { get; set; }
        public int SalaryId { get; set; }
        public Nullable<double> DormFee { get; set; }
        public Nullable<double> Reduction { get; set; }
    
        public virtual Salary Salary { get; set; }
    }
}
